### PR TITLE
Add Support for RHEL / CentOS 7 and Bug Fixes

### PR DESCRIPTION
**Pull request by sammcj**
- Updated and tested against CentOS 7.x and Debian Jessie
- Update DRBD package name for CentOS 7, Debian Wheezy, Debian Jessie
- Correct systemd service file permissions if package incorrectly made them executable (looking at you CentOS 7!)
- Correct permissions on /etc/drbd.d directory
- Correct permissions on /drbd directory
- Add in some additional options that can be passed to DRBD resources
- Add the ability to allow the module to update the DRBD package if enabled

While this update may not be perfect, it's a lot more usable than the 2012 version and as been working for us in production for over a year across many hosts.

PR's on my PR accepted ;)

### CODE REVIEW

**Comment by jyaworski** [comment]
@sammcj can you rebase on the current master?

**Comment by sammcj** [comment]
OK I'll give it a go, I've never been in this situation with git and this far behind before, bear with me.

**Comment by sammcj** [comment]
Yeahhhh OK I totally failed at that, I might have to get one of the devs at work tomorrow to help me out! I'm an Ops engineer and storage architect so while I use git 5-30 times a day, it's mostly rebase, pull, commit, push etc...

**Comment by sammcj** [comment]
Added you as a collaborator to my fork incase you know what to do and need it asap

**Comment by ekohl** [comment]
This needs a rebase now.

**Pull request closed without merging**
