### PR TITLE
Extend resourceopt

### PR DESCRIPTION
**Pull request by Slm0n87**
- contains https://github.com/puppetlabs/puppetlabs-drbd/pull/1
- extended resource-options for resource.pp

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @Slm0n87, can you please take a look at the merge conflicts?

**Comment by Slm0n87** [comment]
merge conflicts solved.

**Comment by bastelfreak** [comment]
@Slm0n87 is it possible that you add a few tests? Than I'm happy to merge.

**Comment by ekohl** [comment]
This needs a rebase now

**Comment by bastelfreak** [comment]
Hello. I'm going to close this PR due to inactivity. Please reopen and rebase it if you're still interested in it.

**Pull request closed without merging**
